<?php

namespace App\Support;

/**
 * AUTO-GENERATED from countries-list. Do not edit by hand —
 * run `node scripts/generate-countries.cjs` to regenerate.
 *
 * Shared ISO 3166-1 alpha-2 country dataset. The frontend persists a
 * country_iso ("IN", "GB") alongside the dialling prefix so a shared prefix
 * (+44 → GB/JE/GG/IM, +1 → US/CA) still resolves to one exact flag.
 */
class Countries
{
    /** @var list<array{iso: string, dial: string, name: string}> */
    public const ALL = [
        ['iso' => 'AF', 'dial' => '+93', 'name' => 'Afghanistan'],
        ['iso' => 'AX', 'dial' => '+358', 'name' => 'Aland'],
        ['iso' => 'AL', 'dial' => '+355', 'name' => 'Albania'],
        ['iso' => 'DZ', 'dial' => '+213', 'name' => 'Algeria'],
        ['iso' => 'AS', 'dial' => '+1684', 'name' => 'American Samoa'],
        ['iso' => 'AD', 'dial' => '+376', 'name' => 'Andorra'],
        ['iso' => 'AO', 'dial' => '+244', 'name' => 'Angola'],
        ['iso' => 'AI', 'dial' => '+1264', 'name' => 'Anguilla'],
        ['iso' => 'AQ', 'dial' => '+672', 'name' => 'Antarctica'],
        ['iso' => 'AG', 'dial' => '+1268', 'name' => 'Antigua and Barbuda'],
        ['iso' => 'AR', 'dial' => '+54', 'name' => 'Argentina'],
        ['iso' => 'AM', 'dial' => '+374', 'name' => 'Armenia'],
        ['iso' => 'AW', 'dial' => '+297', 'name' => 'Aruba'],
        ['iso' => 'AC', 'dial' => '+247', 'name' => 'Ascension Island'],
        ['iso' => 'AU', 'dial' => '+61', 'name' => 'Australia'],
        ['iso' => 'AT', 'dial' => '+43', 'name' => 'Austria'],
        ['iso' => 'AZ', 'dial' => '+994', 'name' => 'Azerbaijan'],
        ['iso' => 'BS', 'dial' => '+1242', 'name' => 'Bahamas'],
        ['iso' => 'BH', 'dial' => '+973', 'name' => 'Bahrain'],
        ['iso' => 'BD', 'dial' => '+880', 'name' => 'Bangladesh'],
        ['iso' => 'BB', 'dial' => '+1246', 'name' => 'Barbados'],
        ['iso' => 'BY', 'dial' => '+375', 'name' => 'Belarus'],
        ['iso' => 'BE', 'dial' => '+32', 'name' => 'Belgium'],
        ['iso' => 'BZ', 'dial' => '+501', 'name' => 'Belize'],
        ['iso' => 'BJ', 'dial' => '+229', 'name' => 'Benin'],
        ['iso' => 'BM', 'dial' => '+1441', 'name' => 'Bermuda'],
        ['iso' => 'BT', 'dial' => '+975', 'name' => 'Bhutan'],
        ['iso' => 'BO', 'dial' => '+591', 'name' => 'Bolivia'],
        ['iso' => 'BQ', 'dial' => '+5997', 'name' => 'Bonaire'],
        ['iso' => 'BA', 'dial' => '+387', 'name' => 'Bosnia and Herzegovina'],
        ['iso' => 'BW', 'dial' => '+267', 'name' => 'Botswana'],
        ['iso' => 'BV', 'dial' => '+47', 'name' => 'Bouvet Island'],
        ['iso' => 'BR', 'dial' => '+55', 'name' => 'Brazil'],
        ['iso' => 'IO', 'dial' => '+246', 'name' => 'British Indian Ocean Territory'],
        ['iso' => 'VG', 'dial' => '+1284', 'name' => 'British Virgin Islands'],
        ['iso' => 'BN', 'dial' => '+673', 'name' => 'Brunei'],
        ['iso' => 'BG', 'dial' => '+359', 'name' => 'Bulgaria'],
        ['iso' => 'BF', 'dial' => '+226', 'name' => 'Burkina Faso'],
        ['iso' => 'BI', 'dial' => '+257', 'name' => 'Burundi'],
        ['iso' => 'KH', 'dial' => '+855', 'name' => 'Cambodia'],
        ['iso' => 'CM', 'dial' => '+237', 'name' => 'Cameroon'],
        ['iso' => 'CA', 'dial' => '+1', 'name' => 'Canada'],
        ['iso' => 'CV', 'dial' => '+238', 'name' => 'Cape Verde'],
        ['iso' => 'KY', 'dial' => '+1345', 'name' => 'Cayman Islands'],
        ['iso' => 'CF', 'dial' => '+236', 'name' => 'Central African Republic'],
        ['iso' => 'TD', 'dial' => '+235', 'name' => 'Chad'],
        ['iso' => 'CL', 'dial' => '+56', 'name' => 'Chile'],
        ['iso' => 'CN', 'dial' => '+86', 'name' => 'China'],
        ['iso' => 'CX', 'dial' => '+61', 'name' => 'Christmas Island'],
        ['iso' => 'CC', 'dial' => '+61', 'name' => 'Cocos (Keeling) Islands'],
        ['iso' => 'CO', 'dial' => '+57', 'name' => 'Colombia'],
        ['iso' => 'KM', 'dial' => '+269', 'name' => 'Comoros'],
        ['iso' => 'CK', 'dial' => '+682', 'name' => 'Cook Islands'],
        ['iso' => 'CR', 'dial' => '+506', 'name' => 'Costa Rica'],
        ['iso' => 'HR', 'dial' => '+385', 'name' => 'Croatia'],
        ['iso' => 'CU', 'dial' => '+53', 'name' => 'Cuba'],
        ['iso' => 'CW', 'dial' => '+5999', 'name' => 'Curacao'],
        ['iso' => 'CY', 'dial' => '+357', 'name' => 'Cyprus'],
        ['iso' => 'CZ', 'dial' => '+420', 'name' => 'Czech Republic'],
        ['iso' => 'CD', 'dial' => '+243', 'name' => 'Democratic Republic of the Congo'],
        ['iso' => 'DK', 'dial' => '+45', 'name' => 'Denmark'],
        ['iso' => 'DJ', 'dial' => '+253', 'name' => 'Djibouti'],
        ['iso' => 'DM', 'dial' => '+1767', 'name' => 'Dominica'],
        ['iso' => 'DO', 'dial' => '+1809', 'name' => 'Dominican Republic'],
        ['iso' => 'TL', 'dial' => '+670', 'name' => 'East Timor'],
        ['iso' => 'EC', 'dial' => '+593', 'name' => 'Ecuador'],
        ['iso' => 'EG', 'dial' => '+20', 'name' => 'Egypt'],
        ['iso' => 'SV', 'dial' => '+503', 'name' => 'El Salvador'],
        ['iso' => 'GQ', 'dial' => '+240', 'name' => 'Equatorial Guinea'],
        ['iso' => 'ER', 'dial' => '+291', 'name' => 'Eritrea'],
        ['iso' => 'EE', 'dial' => '+372', 'name' => 'Estonia'],
        ['iso' => 'SZ', 'dial' => '+268', 'name' => 'Eswatini'],
        ['iso' => 'ET', 'dial' => '+251', 'name' => 'Ethiopia'],
        ['iso' => 'FK', 'dial' => '+500', 'name' => 'Falkland Islands'],
        ['iso' => 'FO', 'dial' => '+298', 'name' => 'Faroe Islands'],
        ['iso' => 'FJ', 'dial' => '+679', 'name' => 'Fiji'],
        ['iso' => 'FI', 'dial' => '+358', 'name' => 'Finland'],
        ['iso' => 'FR', 'dial' => '+33', 'name' => 'France'],
        ['iso' => 'GF', 'dial' => '+594', 'name' => 'French Guiana'],
        ['iso' => 'PF', 'dial' => '+689', 'name' => 'French Polynesia'],
        ['iso' => 'TF', 'dial' => '+262', 'name' => 'French Southern Territories'],
        ['iso' => 'GA', 'dial' => '+241', 'name' => 'Gabon'],
        ['iso' => 'GM', 'dial' => '+220', 'name' => 'Gambia'],
        ['iso' => 'GE', 'dial' => '+995', 'name' => 'Georgia'],
        ['iso' => 'DE', 'dial' => '+49', 'name' => 'Germany'],
        ['iso' => 'GH', 'dial' => '+233', 'name' => 'Ghana'],
        ['iso' => 'GI', 'dial' => '+350', 'name' => 'Gibraltar'],
        ['iso' => 'GR', 'dial' => '+30', 'name' => 'Greece'],
        ['iso' => 'GL', 'dial' => '+299', 'name' => 'Greenland'],
        ['iso' => 'GD', 'dial' => '+1473', 'name' => 'Grenada'],
        ['iso' => 'GP', 'dial' => '+590', 'name' => 'Guadeloupe'],
        ['iso' => 'GU', 'dial' => '+1671', 'name' => 'Guam'],
        ['iso' => 'GT', 'dial' => '+502', 'name' => 'Guatemala'],
        ['iso' => 'GG', 'dial' => '+44', 'name' => 'Guernsey'],
        ['iso' => 'GN', 'dial' => '+224', 'name' => 'Guinea'],
        ['iso' => 'GW', 'dial' => '+245', 'name' => 'Guinea-Bissau'],
        ['iso' => 'GY', 'dial' => '+592', 'name' => 'Guyana'],
        ['iso' => 'HT', 'dial' => '+509', 'name' => 'Haiti'],
        ['iso' => 'HM', 'dial' => '+61', 'name' => 'Heard Island and McDonald Islands'],
        ['iso' => 'HN', 'dial' => '+504', 'name' => 'Honduras'],
        ['iso' => 'HK', 'dial' => '+852', 'name' => 'Hong Kong'],
        ['iso' => 'HU', 'dial' => '+36', 'name' => 'Hungary'],
        ['iso' => 'IS', 'dial' => '+354', 'name' => 'Iceland'],
        ['iso' => 'IN', 'dial' => '+91', 'name' => 'India'],
        ['iso' => 'ID', 'dial' => '+62', 'name' => 'Indonesia'],
        ['iso' => 'IR', 'dial' => '+98', 'name' => 'Iran'],
        ['iso' => 'IQ', 'dial' => '+964', 'name' => 'Iraq'],
        ['iso' => 'IE', 'dial' => '+353', 'name' => 'Ireland'],
        ['iso' => 'IM', 'dial' => '+44', 'name' => 'Isle of Man'],
        ['iso' => 'IL', 'dial' => '+972', 'name' => 'Israel'],
        ['iso' => 'IT', 'dial' => '+39', 'name' => 'Italy'],
        ['iso' => 'CI', 'dial' => '+225', 'name' => 'Ivory Coast'],
        ['iso' => 'JM', 'dial' => '+1876', 'name' => 'Jamaica'],
        ['iso' => 'JP', 'dial' => '+81', 'name' => 'Japan'],
        ['iso' => 'JE', 'dial' => '+44', 'name' => 'Jersey'],
        ['iso' => 'JO', 'dial' => '+962', 'name' => 'Jordan'],
        ['iso' => 'KZ', 'dial' => '+7', 'name' => 'Kazakhstan'],
        ['iso' => 'KE', 'dial' => '+254', 'name' => 'Kenya'],
        ['iso' => 'KI', 'dial' => '+686', 'name' => 'Kiribati'],
        ['iso' => 'XK', 'dial' => '+377', 'name' => 'Kosovo'],
        ['iso' => 'KW', 'dial' => '+965', 'name' => 'Kuwait'],
        ['iso' => 'KG', 'dial' => '+996', 'name' => 'Kyrgyzstan'],
        ['iso' => 'LA', 'dial' => '+856', 'name' => 'Laos'],
        ['iso' => 'LV', 'dial' => '+371', 'name' => 'Latvia'],
        ['iso' => 'LB', 'dial' => '+961', 'name' => 'Lebanon'],
        ['iso' => 'LS', 'dial' => '+266', 'name' => 'Lesotho'],
        ['iso' => 'LR', 'dial' => '+231', 'name' => 'Liberia'],
        ['iso' => 'LY', 'dial' => '+218', 'name' => 'Libya'],
        ['iso' => 'LI', 'dial' => '+423', 'name' => 'Liechtenstein'],
        ['iso' => 'LT', 'dial' => '+370', 'name' => 'Lithuania'],
        ['iso' => 'LU', 'dial' => '+352', 'name' => 'Luxembourg'],
        ['iso' => 'MO', 'dial' => '+853', 'name' => 'Macao'],
        ['iso' => 'MG', 'dial' => '+261', 'name' => 'Madagascar'],
        ['iso' => 'MW', 'dial' => '+265', 'name' => 'Malawi'],
        ['iso' => 'MY', 'dial' => '+60', 'name' => 'Malaysia'],
        ['iso' => 'MV', 'dial' => '+960', 'name' => 'Maldives'],
        ['iso' => 'ML', 'dial' => '+223', 'name' => 'Mali'],
        ['iso' => 'MT', 'dial' => '+356', 'name' => 'Malta'],
        ['iso' => 'MH', 'dial' => '+692', 'name' => 'Marshall Islands'],
        ['iso' => 'MQ', 'dial' => '+596', 'name' => 'Martinique'],
        ['iso' => 'MR', 'dial' => '+222', 'name' => 'Mauritania'],
        ['iso' => 'MU', 'dial' => '+230', 'name' => 'Mauritius'],
        ['iso' => 'YT', 'dial' => '+262', 'name' => 'Mayotte'],
        ['iso' => 'MX', 'dial' => '+52', 'name' => 'Mexico'],
        ['iso' => 'FM', 'dial' => '+691', 'name' => 'Micronesia'],
        ['iso' => 'MD', 'dial' => '+373', 'name' => 'Moldova'],
        ['iso' => 'MC', 'dial' => '+377', 'name' => 'Monaco'],
        ['iso' => 'MN', 'dial' => '+976', 'name' => 'Mongolia'],
        ['iso' => 'ME', 'dial' => '+382', 'name' => 'Montenegro'],
        ['iso' => 'MS', 'dial' => '+1664', 'name' => 'Montserrat'],
        ['iso' => 'MA', 'dial' => '+212', 'name' => 'Morocco'],
        ['iso' => 'MZ', 'dial' => '+258', 'name' => 'Mozambique'],
        ['iso' => 'MM', 'dial' => '+95', 'name' => 'Myanmar (Burma)'],
        ['iso' => 'NA', 'dial' => '+264', 'name' => 'Namibia'],
        ['iso' => 'NR', 'dial' => '+674', 'name' => 'Nauru'],
        ['iso' => 'NP', 'dial' => '+977', 'name' => 'Nepal'],
        ['iso' => 'NL', 'dial' => '+31', 'name' => 'Netherlands'],
        ['iso' => 'NC', 'dial' => '+687', 'name' => 'New Caledonia'],
        ['iso' => 'NZ', 'dial' => '+64', 'name' => 'New Zealand'],
        ['iso' => 'NI', 'dial' => '+505', 'name' => 'Nicaragua'],
        ['iso' => 'NE', 'dial' => '+227', 'name' => 'Niger'],
        ['iso' => 'NG', 'dial' => '+234', 'name' => 'Nigeria'],
        ['iso' => 'NU', 'dial' => '+683', 'name' => 'Niue'],
        ['iso' => 'NF', 'dial' => '+672', 'name' => 'Norfolk Island'],
        ['iso' => 'KP', 'dial' => '+850', 'name' => 'North Korea'],
        ['iso' => 'MK', 'dial' => '+389', 'name' => 'North Macedonia'],
        ['iso' => 'MP', 'dial' => '+1670', 'name' => 'Northern Mariana Islands'],
        ['iso' => 'NO', 'dial' => '+47', 'name' => 'Norway'],
        ['iso' => 'OM', 'dial' => '+968', 'name' => 'Oman'],
        ['iso' => 'PK', 'dial' => '+92', 'name' => 'Pakistan'],
        ['iso' => 'PW', 'dial' => '+680', 'name' => 'Palau'],
        ['iso' => 'PS', 'dial' => '+970', 'name' => 'Palestine'],
        ['iso' => 'PA', 'dial' => '+507', 'name' => 'Panama'],
        ['iso' => 'PG', 'dial' => '+675', 'name' => 'Papua New Guinea'],
        ['iso' => 'PY', 'dial' => '+595', 'name' => 'Paraguay'],
        ['iso' => 'PE', 'dial' => '+51', 'name' => 'Peru'],
        ['iso' => 'PH', 'dial' => '+63', 'name' => 'Philippines'],
        ['iso' => 'PN', 'dial' => '+64', 'name' => 'Pitcairn Islands'],
        ['iso' => 'PL', 'dial' => '+48', 'name' => 'Poland'],
        ['iso' => 'PT', 'dial' => '+351', 'name' => 'Portugal'],
        ['iso' => 'PR', 'dial' => '+1787', 'name' => 'Puerto Rico'],
        ['iso' => 'QA', 'dial' => '+974', 'name' => 'Qatar'],
        ['iso' => 'CG', 'dial' => '+242', 'name' => 'Republic of the Congo'],
        ['iso' => 'RE', 'dial' => '+262', 'name' => 'Reunion'],
        ['iso' => 'RO', 'dial' => '+40', 'name' => 'Romania'],
        ['iso' => 'RU', 'dial' => '+7', 'name' => 'Russia'],
        ['iso' => 'RW', 'dial' => '+250', 'name' => 'Rwanda'],
        ['iso' => 'BL', 'dial' => '+590', 'name' => 'Saint Barthelemy'],
        ['iso' => 'SH', 'dial' => '+290', 'name' => 'Saint Helena'],
        ['iso' => 'KN', 'dial' => '+1869', 'name' => 'Saint Kitts and Nevis'],
        ['iso' => 'LC', 'dial' => '+1758', 'name' => 'Saint Lucia'],
        ['iso' => 'MF', 'dial' => '+590', 'name' => 'Saint Martin'],
        ['iso' => 'PM', 'dial' => '+508', 'name' => 'Saint Pierre and Miquelon'],
        ['iso' => 'VC', 'dial' => '+1784', 'name' => 'Saint Vincent and the Grenadines'],
        ['iso' => 'WS', 'dial' => '+685', 'name' => 'Samoa'],
        ['iso' => 'SM', 'dial' => '+378', 'name' => 'San Marino'],
        ['iso' => 'ST', 'dial' => '+239', 'name' => 'Sao Tome and Principe'],
        ['iso' => 'SA', 'dial' => '+966', 'name' => 'Saudi Arabia'],
        ['iso' => 'SN', 'dial' => '+221', 'name' => 'Senegal'],
        ['iso' => 'RS', 'dial' => '+381', 'name' => 'Serbia'],
        ['iso' => 'SC', 'dial' => '+248', 'name' => 'Seychelles'],
        ['iso' => 'SL', 'dial' => '+232', 'name' => 'Sierra Leone'],
        ['iso' => 'SG', 'dial' => '+65', 'name' => 'Singapore'],
        ['iso' => 'SX', 'dial' => '+1721', 'name' => 'Sint Maarten'],
        ['iso' => 'SK', 'dial' => '+421', 'name' => 'Slovakia'],
        ['iso' => 'SI', 'dial' => '+386', 'name' => 'Slovenia'],
        ['iso' => 'SB', 'dial' => '+677', 'name' => 'Solomon Islands'],
        ['iso' => 'SO', 'dial' => '+252', 'name' => 'Somalia'],
        ['iso' => 'ZA', 'dial' => '+27', 'name' => 'South Africa'],
        ['iso' => 'GS', 'dial' => '+500', 'name' => 'South Georgia and the South Sandwich Islands'],
        ['iso' => 'KR', 'dial' => '+82', 'name' => 'South Korea'],
        ['iso' => 'SS', 'dial' => '+211', 'name' => 'South Sudan'],
        ['iso' => 'ES', 'dial' => '+34', 'name' => 'Spain'],
        ['iso' => 'LK', 'dial' => '+94', 'name' => 'Sri Lanka'],
        ['iso' => 'SD', 'dial' => '+249', 'name' => 'Sudan'],
        ['iso' => 'SR', 'dial' => '+597', 'name' => 'Suriname'],
        ['iso' => 'SJ', 'dial' => '+4779', 'name' => 'Svalbard and Jan Mayen'],
        ['iso' => 'SE', 'dial' => '+46', 'name' => 'Sweden'],
        ['iso' => 'CH', 'dial' => '+41', 'name' => 'Switzerland'],
        ['iso' => 'SY', 'dial' => '+963', 'name' => 'Syria'],
        ['iso' => 'TW', 'dial' => '+886', 'name' => 'Taiwan'],
        ['iso' => 'TJ', 'dial' => '+992', 'name' => 'Tajikistan'],
        ['iso' => 'TZ', 'dial' => '+255', 'name' => 'Tanzania'],
        ['iso' => 'TH', 'dial' => '+66', 'name' => 'Thailand'],
        ['iso' => 'TG', 'dial' => '+228', 'name' => 'Togo'],
        ['iso' => 'TK', 'dial' => '+690', 'name' => 'Tokelau'],
        ['iso' => 'TO', 'dial' => '+676', 'name' => 'Tonga'],
        ['iso' => 'TT', 'dial' => '+1868', 'name' => 'Trinidad and Tobago'],
        ['iso' => 'TA', 'dial' => '+290', 'name' => 'Tristan da Cunha'],
        ['iso' => 'TN', 'dial' => '+216', 'name' => 'Tunisia'],
        ['iso' => 'TR', 'dial' => '+90', 'name' => 'Türkiye'],
        ['iso' => 'TM', 'dial' => '+993', 'name' => 'Turkmenistan'],
        ['iso' => 'TC', 'dial' => '+1649', 'name' => 'Turks and Caicos Islands'],
        ['iso' => 'TV', 'dial' => '+688', 'name' => 'Tuvalu'],
        ['iso' => 'UM', 'dial' => '+1', 'name' => 'U.S. Minor Outlying Islands'],
        ['iso' => 'VI', 'dial' => '+1340', 'name' => 'U.S. Virgin Islands'],
        ['iso' => 'UG', 'dial' => '+256', 'name' => 'Uganda'],
        ['iso' => 'UA', 'dial' => '+380', 'name' => 'Ukraine'],
        ['iso' => 'AE', 'dial' => '+971', 'name' => 'United Arab Emirates'],
        ['iso' => 'GB', 'dial' => '+44', 'name' => 'United Kingdom'],
        ['iso' => 'US', 'dial' => '+1', 'name' => 'United States'],
        ['iso' => 'UY', 'dial' => '+598', 'name' => 'Uruguay'],
        ['iso' => 'UZ', 'dial' => '+998', 'name' => 'Uzbekistan'],
        ['iso' => 'VU', 'dial' => '+678', 'name' => 'Vanuatu'],
        ['iso' => 'VA', 'dial' => '+379', 'name' => 'Vatican City'],
        ['iso' => 'VE', 'dial' => '+58', 'name' => 'Venezuela'],
        ['iso' => 'VN', 'dial' => '+84', 'name' => 'Vietnam'],
        ['iso' => 'WF', 'dial' => '+681', 'name' => 'Wallis and Futuna'],
        ['iso' => 'EH', 'dial' => '+212', 'name' => 'Western Sahara'],
        ['iso' => 'YE', 'dial' => '+967', 'name' => 'Yemen'],
        ['iso' => 'ZM', 'dial' => '+260', 'name' => 'Zambia'],
        ['iso' => 'ZW', 'dial' => '+263', 'name' => 'Zimbabwe'],
    ];

    /**
     * Most canonical country for a shared dialling prefix — used to derive an
     * ISO when only the dial code is known (legacy rows / fallback).
     *
     * @var array<string, string>
     */
    private const PRIMARY_ISO_BY_DIAL = [
        '+1' => 'US',
        '+1242' => 'BS',
        '+1246' => 'BB',
        '+1264' => 'AI',
        '+1268' => 'AG',
        '+1284' => 'VG',
        '+1340' => 'VI',
        '+1345' => 'KY',
        '+1441' => 'BM',
        '+1473' => 'GD',
        '+1649' => 'TC',
        '+1664' => 'MS',
        '+1670' => 'MP',
        '+1671' => 'GU',
        '+1684' => 'AS',
        '+1721' => 'SX',
        '+1758' => 'LC',
        '+1767' => 'DM',
        '+1784' => 'VC',
        '+1787' => 'PR',
        '+1809' => 'DO',
        '+1868' => 'TT',
        '+1869' => 'KN',
        '+1876' => 'JM',
        '+20' => 'EG',
        '+211' => 'SS',
        '+212' => 'MA',
        '+213' => 'DZ',
        '+216' => 'TN',
        '+218' => 'LY',
        '+220' => 'GM',
        '+221' => 'SN',
        '+222' => 'MR',
        '+223' => 'ML',
        '+224' => 'GN',
        '+225' => 'CI',
        '+226' => 'BF',
        '+227' => 'NE',
        '+228' => 'TG',
        '+229' => 'BJ',
        '+230' => 'MU',
        '+231' => 'LR',
        '+232' => 'SL',
        '+233' => 'GH',
        '+234' => 'NG',
        '+235' => 'TD',
        '+236' => 'CF',
        '+237' => 'CM',
        '+238' => 'CV',
        '+239' => 'ST',
        '+240' => 'GQ',
        '+241' => 'GA',
        '+242' => 'CG',
        '+243' => 'CD',
        '+244' => 'AO',
        '+245' => 'GW',
        '+246' => 'IO',
        '+247' => 'AC',
        '+248' => 'SC',
        '+249' => 'SD',
        '+250' => 'RW',
        '+251' => 'ET',
        '+252' => 'SO',
        '+253' => 'DJ',
        '+254' => 'KE',
        '+255' => 'TZ',
        '+256' => 'UG',
        '+257' => 'BI',
        '+258' => 'MZ',
        '+260' => 'ZM',
        '+261' => 'MG',
        '+262' => 'RE',
        '+263' => 'ZW',
        '+264' => 'NA',
        '+265' => 'MW',
        '+266' => 'LS',
        '+267' => 'BW',
        '+268' => 'SZ',
        '+269' => 'KM',
        '+27' => 'ZA',
        '+290' => 'SH',
        '+291' => 'ER',
        '+297' => 'AW',
        '+298' => 'FO',
        '+299' => 'GL',
        '+30' => 'GR',
        '+31' => 'NL',
        '+32' => 'BE',
        '+33' => 'FR',
        '+34' => 'ES',
        '+350' => 'GI',
        '+351' => 'PT',
        '+352' => 'LU',
        '+353' => 'IE',
        '+354' => 'IS',
        '+355' => 'AL',
        '+356' => 'MT',
        '+357' => 'CY',
        '+358' => 'FI',
        '+359' => 'BG',
        '+36' => 'HU',
        '+370' => 'LT',
        '+371' => 'LV',
        '+372' => 'EE',
        '+373' => 'MD',
        '+374' => 'AM',
        '+375' => 'BY',
        '+376' => 'AD',
        '+377' => 'MC',
        '+378' => 'SM',
        '+379' => 'VA',
        '+380' => 'UA',
        '+381' => 'RS',
        '+382' => 'ME',
        '+385' => 'HR',
        '+386' => 'SI',
        '+387' => 'BA',
        '+389' => 'MK',
        '+39' => 'IT',
        '+40' => 'RO',
        '+41' => 'CH',
        '+420' => 'CZ',
        '+421' => 'SK',
        '+423' => 'LI',
        '+43' => 'AT',
        '+44' => 'GB',
        '+45' => 'DK',
        '+46' => 'SE',
        '+47' => 'NO',
        '+4779' => 'SJ',
        '+48' => 'PL',
        '+49' => 'DE',
        '+500' => 'FK',
        '+501' => 'BZ',
        '+502' => 'GT',
        '+503' => 'SV',
        '+504' => 'HN',
        '+505' => 'NI',
        '+506' => 'CR',
        '+507' => 'PA',
        '+508' => 'PM',
        '+509' => 'HT',
        '+51' => 'PE',
        '+52' => 'MX',
        '+53' => 'CU',
        '+54' => 'AR',
        '+55' => 'BR',
        '+56' => 'CL',
        '+57' => 'CO',
        '+58' => 'VE',
        '+590' => 'GP',
        '+591' => 'BO',
        '+592' => 'GY',
        '+593' => 'EC',
        '+594' => 'GF',
        '+595' => 'PY',
        '+596' => 'MQ',
        '+597' => 'SR',
        '+598' => 'UY',
        '+5997' => 'BQ',
        '+5999' => 'CW',
        '+60' => 'MY',
        '+61' => 'AU',
        '+62' => 'ID',
        '+63' => 'PH',
        '+64' => 'NZ',
        '+65' => 'SG',
        '+66' => 'TH',
        '+670' => 'TL',
        '+672' => 'NF',
        '+673' => 'BN',
        '+674' => 'NR',
        '+675' => 'PG',
        '+676' => 'TO',
        '+677' => 'SB',
        '+678' => 'VU',
        '+679' => 'FJ',
        '+680' => 'PW',
        '+681' => 'WF',
        '+682' => 'CK',
        '+683' => 'NU',
        '+685' => 'WS',
        '+686' => 'KI',
        '+687' => 'NC',
        '+688' => 'TV',
        '+689' => 'PF',
        '+690' => 'TK',
        '+691' => 'FM',
        '+692' => 'MH',
        '+7' => 'RU',
        '+81' => 'JP',
        '+82' => 'KR',
        '+84' => 'VN',
        '+850' => 'KP',
        '+852' => 'HK',
        '+853' => 'MO',
        '+855' => 'KH',
        '+856' => 'LA',
        '+86' => 'CN',
        '+880' => 'BD',
        '+886' => 'TW',
        '+90' => 'TR',
        '+91' => 'IN',
        '+92' => 'PK',
        '+93' => 'AF',
        '+94' => 'LK',
        '+95' => 'MM',
        '+960' => 'MV',
        '+961' => 'LB',
        '+962' => 'JO',
        '+963' => 'SY',
        '+964' => 'IQ',
        '+965' => 'KW',
        '+966' => 'SA',
        '+967' => 'YE',
        '+968' => 'OM',
        '+970' => 'PS',
        '+971' => 'AE',
        '+972' => 'IL',
        '+973' => 'BH',
        '+974' => 'QA',
        '+975' => 'BT',
        '+976' => 'MN',
        '+977' => 'NP',
        '+98' => 'IR',
        '+992' => 'TJ',
        '+993' => 'TM',
        '+994' => 'AZ',
        '+995' => 'GE',
        '+996' => 'KG',
        '+998' => 'UZ',
    ];

    /** @return list<array{iso: string, dial: string, name: string}> */
    public static function all(): array
    {
        return self::ALL;
    }

    public static function isValidIso(?string $iso): bool
    {
        if ($iso === null || $iso === '') {
            return false;
        }

        $upper = strtoupper($iso);

        foreach (self::ALL as $country) {
            if ($country['iso'] === $upper) {
                return true;
            }
        }

        return false;
    }

    public static function primaryIsoForDial(?string $dial): ?string
    {
        return $dial === null ? null : (self::PRIMARY_ISO_BY_DIAL[$dial] ?? null);
    }

    public static function dialForIso(?string $iso): ?string
    {
        if ($iso === null || $iso === '') {
            return null;
        }

        $upper = strtoupper($iso);

        foreach (self::ALL as $country) {
            if ($country['iso'] === $upper) {
                return $country['dial'];
            }
        }

        return null;
    }
}
